const watches = [
  {
    id: 1,
    title: "Regency Royale Digital",
    slug: "regency-royale-digital",
    price: 374.0,
    image: "/images/product-main-15.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 2,
    title: "Elite Enigma Digital",
    slug: "elite-enigma-digital",
    price: 290.0,
    image: "/images/product-main-12.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 3,
    title: "Royal Crest Sovereign Signature",
    slug: "royal-crest-sovereign-signature",
    price: 320.0,
    image: "/images/product-main-19.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 4,
    title: "Zenith Zephyr",
    slug: "zenith-zephyr",
    price: 210.0,
    image: "/images/product-main-16.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 5,
    title: "Timeless Elegance",
    slug: "timeless-elegance",
    price: 220.0,
    image: "/images/product-main-10.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 6,
    title: "Sovereign Signature",
    slug: "sovereign-signature",
    price: 405.0,
    image: "/images/product-main-07.png",
    discount: null,
    oldPrice: 430.0,
  },
  {
    id: 7,
    title: "Mastercraft Chrono",
    slug: "mastercraft-chrono",
    price: 298.0,
    image: "/images/product-main-04.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 8,
    title: "Supreme Sapphire",
    slug: "supreme-sapphire",
    price: 355.0,
    image: "/images/product-main-03.png",
    discount: "-15%",
    oldPrice: null,
  },
  {
    id: 9,
    title: "Noble Chronograph",
    slug: "noble-chronograph",
    price: 320.0,
    image: "/images/product-main-01.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 10,
    title: "Celestial Majesty Timekeeper Elite",
    slug: "celestial-majesty-timekeeper-elite",
    price: 395.0,
    image: "/images/product-main-21.png",
    discount: null,
    oldPrice: null,
  },
  {
    id: 11,
    title: "Timeless Tradition Classic Legacy",
    slug: "timeless-tradition-classic-legacy",
    price: 470.0,
    image: "/images/product-main-20.png",
    discount: "-35%",
    oldPrice: null,
  },
  {
    id: 12,
    title: "Prestige Proxima",
    slug: "prestige-proxima",
    price: 295.0,
    image: "/images/product-main-18.png",
    discount: null,
    oldPrice: null,
  },
]

export default watches
